export const PREVIEW_CONSTS = {
  MESSAGE_TYPES: {
    READY: 'NGX_PAGE_PREVIEW_READY',
    GET_DATA: 'NGX_PAGE_PREVIEW_GET_DATA',
    LOAD_ENDED: 'NGX_PAGE_PREVIEW_LOAD_ENDED',
    CLOSE: 'NGX_PAGE_PREVIEW_CLOSE',
  },
  TIMEOUT_READY: 2000,
  TIMEOUT_LOAD_FONTS: 5000,
};
